---
title: "assignment"
output: html_document
date: "2026-03-04"
---

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub) # to fetch genomes, annotations, etc.
  library(ensembldb)     # to manipulate ensembl gene annotations
  library(GenomicRanges) # data structure for genomic ranges 
  library(epiwraps)      # visualization
})
```

```{r}
ah <- AnnotationHub()
query_results_mouse <- query(ah, c("Mus Musculus", "EnsDb", "version 102", "GRCm38"))
query_results_mouse
mouse_EnsDb <- ah[["AH89211"]]
mouse_EnsDb


query_results_mouse_dna <- query(ah, c("Mus Musculus", "dna_sm", "2bit", "GRCm38"))
query_results_mouse_dna$rdatadateadded
rev(query_results_mouse_dna$ah_id)[1]
mouse_dnaseq <- ah[["AH88477"]]
mouse_dnaseq

query_results_fly <- query(ah, c("Drosophila", "dna_sm", "2bit", "BDGP6"))
query_results_fly$rdatadateadded
rev(query_results_fly$ah_id)[1]
fly_dnaseq <- ah[["AH106160"]]
fly_dnaseq
```


```{r}
mouse_genes <- genes(mouse_EnsDb)
head(mouse_genes)

mouse_pcg <- mouse_genes[mouse_genes$gene_biotype=="protein_coding"]
length(unique(mouse_pcg$gene_id))
length(unique(mouse_pcg$symbol))
```
```{r}
mouse_Tx <- transcripts(mouse_EnsDb)
mouse_pct <- mouse_Tx[mouse_Tx$tx_biotype=="protein_coding"]
mouse_pct
# mcols(mouse_pct)
mouse_ex <- exons(mouse_EnsDb, columns = c("gene_id"))
head(mouse_ex)

mouse_ex_by <- exonsBy(mouse_EnsDb)
head(mouse_ex_by)
#which(mouse_pct$gene_id %in% mouse_ex$gene_id)

o <- overlapsAny(mouse_ex, mouse_pct)
o
mouse_ex[o,]
```

